name: build and run
on:
  - push
jobs:
  build20:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
    - name: prepare build
      run: mkdir build
    - name: build
      run: javac --source 20 --enable-preview --add-exports java.base/jdk.internal.vm=YieldReturn -d build src/module-info.java src/io/github/danthe1st/jvmyieldreturn/*.java src/io/github/danthe1st/jvmyieldreturn/test/*.java
    - name: run
      run: java --enable-preview --add-exports java.base/jdk.internal.vm=YieldReturn --module-path build -m YieldReturn/io.github.danthe1st.jvmyieldreturn.test.YieldReturnTest
  build21:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21-ea'
        distribution: 'temurin'
    - name: prepare build
      run: mkdir build
    - name: build
      run: javac --add-exports java.base/jdk.internal.vm=YieldReturn -d build/main src/module-info.java src/io/github/danthe1st/jvmyieldreturn/*.java src/io/github/danthe1st/jvmyieldreturn/test/*.java
    - name: run
      run: java --add-exports java.base/jdk.internal.vm=YieldReturn --module-path build/main -m YieldReturn/io.github.danthe1st.jvmyieldreturn.test.YieldReturnTest
    - name: download test dependencies
      run: |
        mvn -f .github/workflow-utils/test-dependencies.pom dependency:copy-dependencies -Dscope=test -DoutputDirectory=test-dependencies
        curl https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar -o .github/workflow-utils/test-dependencies/launcher.jar
    - name: compile tests
      run: javac --module-path build/main:.github/workflow-utils/test-dependencies -d build/test test/io/github/danthe1st/jvmyieldreturn/tests/*.java
    - name: run tests
      run: java --add-exports java.base/jdk.internal.vm=ALL-UNNAMED -jar .github/workflow-utils/test-dependencies/launcher.jar --disable-ansi-colors --class-path build/main:build/test --select-package io.github.danthe1st.jvmyieldreturn.tests
    - name: generate Javadoc
      run: javadoc -sourcepath src --snippet-path src --add-exports java.base/jdk.internal.vm=YieldReturn -d docs io.github.danthe1st.jvmyieldreturn
    - name: upload Javadoc
      uses: actions/upload-artifact@v3
      with:
        name: Javadocs
        path: docs
